vich_uploader:
    db_driver: orm
    metadata:
        type: attribute # Spécifie l'utilisation des attributs pour la configuration de VichUploaderBundle

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
